project:
  output-dir: docs  

website:
  navbar:
    title: "Gapminder Analysis"
    left:
      - text: "Home"
        href: index.html  
      - text: "Life Expectancy and GDP"
        href: life-gdp.html  
      - text: "Life Expectancy and Population"
        href: life-population.html  
      - text: "Country Analysis"
        href: country.html  
css: styles.css 
theme: vapor 



